; PlatformIO Project Configuration File
;
;   Build options: build flags, source filter
;   Upload options: custom upload port, speed and extra flags
;   Library options: dependencies, extra library storages
;   Advanced options: extra scripting
;
; Please visit documentation for the other options and examples
; https://docs.platformio.org/page/projectconf.html

[env]
platform = atmelavr
board = megaatmega2560
framework = arduino
monitor_speed = 250000
build_unflags = -std=gnu++11
extra_scripts =
	pre:scripts/version.py
lib_deps =
	olikraus/U8g2@^2.36.18

[env:dcs]
build_flags =
	-std=gnu++17
	-D DCSBIOS_DISABLE_SERVO
	-D COMPILE_FOR_DCS=1
	-D COMPILE_FOR_BMS=0
build_src_filter = +<*> -<BMS.cpp>
lib_deps =
	${env.lib_deps}
	DCS-BIOS=https://github.com/DCS-Skunkworks/dcs-bios-arduino-library.git#0.3.13

[env:bms]
build_flags =
	-std=gnu++17
	-D COMPILE_FOR_DCS=0
	-D COMPILE_FOR_BMS=1
build_src_filter = +<*> -<DCS.cpp>
lib_ignore = Modules, AJS37, F16C, FA18C
lib_deps =
	${env.lib_deps}
	bacon8tor/FalconBMSArduinoConnector@^0.4.0
