#!/usr/bin/env python3
"""Convert an image into a PROGMEM XBM array for u8g2's drawXBMP().

    python scripts/splash.py assets/splash.png lib/MainDisplay/Splash.h

Bright pixels become lit, matching what you see drawing white on black, since
that is how the panel reads. Pass --invert for black-on-white artwork.
"""

import argparse
import sys

from PIL import Image

THRESHOLD = 128


def pack(image, invert):
    """Pack to XBM order: LSB of each byte is the leftmost pixel, rows padded
    out to a byte boundary. Matches u8g2_DrawHXBM, which starts at mask = 1."""
    width, height = image.size
    stride = (width + 7) // 8
    data = bytearray(stride * height)
    pixels = image.load()

    for y in range(height):
        for x in range(width):
            lit = pixels[x, y] >= THRESHOLD
            if invert:
                lit = not lit
            if lit:
                data[y * stride + (x >> 3)] |= 1 << (x & 7)

    return data, stride


def main():
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument("source", help="input image, any format Pillow reads")
    parser.add_argument("header", help="C header to write")
    parser.add_argument("--name", default="Splash", help="C identifier prefix")
    parser.add_argument("--invert", action="store_true",
                        help="treat dark pixels as lit, for black-on-white art")
    args = parser.parse_args()

    image = Image.open(args.source)

    # Flatten onto black so transparency resolves the same way every time
    # rather than depending on what the encoder left in the RGB channels.
    if image.mode in ("RGBA", "LA", "P"):
        image = image.convert("RGBA")
        flattened = Image.new("RGBA", image.size, (0, 0, 0, 255))
        flattened.alpha_composite(image)
        image = flattened

    image = image.convert("L")
    width, height = image.size

    # Two levels is a picture drawn in off-white or off-black, which thresholds
    # exactly as intended. More than two means anti-aliasing, which does not.
    levels = sorted(set(image.getdata()))
    if len(levels) > 2:
        print("warning: %d grey levels present, so the art is anti-aliased; "
              "thresholding at %d will look ragged on a 1-bit panel"
              % (len(levels), THRESHOLD), file=sys.stderr)
    elif levels and (levels[0] != 0 or levels[-1] != 255):
        print("note: levels %s, neither pure black nor white, but only two so "
              "the result is unaffected" % levels, file=sys.stderr)

    data, stride = pack(image, args.invert)

    lines = []
    for row in range(0, len(data), 16):
        chunk = data[row:row + 16]
        lines.append("    " + " ".join("0x%02X," % b for b in chunk))

    with open(args.header, "w", newline="\n") as out:
        out.write("// Generated by scripts/splash.py from %s. Do not edit.\n"
                  % args.source.replace("\\", "/"))
        out.write("#pragma once\n\n")
        out.write("#include <stdint.h>\n")
        out.write("#include <avr/pgmspace.h>\n\n")
        out.write("#define %s_WIDTH %d\n" % (args.name.upper(), width))
        out.write("#define %s_HEIGHT %d\n\n" % (args.name.upper(), height))
        out.write("static const uint8_t %sBits[] PROGMEM = {\n" % args.name)
        out.write("\n".join(lines))
        out.write("\n};\n")

    lit = sum(bin(b).count("1") for b in data)
    print("%s: %dx%d, stride %d, %d bytes of PROGMEM, %.0f%% lit"
          % (args.header, width, height, stride, len(data),
             100.0 * lit / (width * height)))


if __name__ == "__main__":
    main()
